config/routes.rb
IdiomPaper::Application.routes.draw do
  resources :idioms

  root 'idioms#index'

end

app/models/idiom.rb
class Idiom < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/idioms_controller.rb
class IdiomsController < ApplicationController
  before_action :set_idiom, only: [:show, :edit, :update, :destroy]

  # GET /idioms
  # GET /idioms.json
  def index
    @idioms = Idiom.all
  end

  # GET /idioms/1
  # GET /idioms/1.json
  def show
    @idiom = Idiom.find(params[:id])
  end

  # GET /idioms/new
  def new
    @idiom = Idiom.new
  end

  # GET /idioms/1/edit
  def edit
  end

  # POST /idioms
  # POST /idioms.json
  def create
    @idiom = Idiom.new(idiom_params)

    respond_to do |format|
      if @idiom.save
        format.html { redirect_to @idiom, notice: 'Idiom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idiom }
      else
        format.html { render action: 'new' }
        format.json { render json: @idiom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idioms/1
  # PATCH/PUT /idioms/1.json
  def update
    respond_to do |format|
      if @idiom.update(idiom_params)
        format.html { redirect_to @idiom, notice: 'Idiom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idiom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idioms/1
  # DELETE /idioms/1.json
  def destroy
    @idiom.destroy
    respond_to do |format|
      format.html { redirect_to idioms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idiom
      @idiom = Idiom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idiom_params
      params.require(:idiom).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idioms_helper.rb
module IdiomsHelper
end

app/views/idioms/_form.html.haml
= form_for @idiom do |f|
  - if @idiom.errors.any?
    #error_explanation
      %h2= "#{pluralize(@idiom.errors.count, "error")} prohibited this idiom from being saved:"
      %ul
        - @idiom.errors.full_messages.each do |msg|
          %li= msg

  .actions
    タイトル
    = f.text_field :title
    意味
    = f.text_area :description
    = f.submit 'Save'

app/views/idioms/edit.html.haml
%h1 Editing idiom

= render 'form'

= link_to 'Show', @idiom
\|
= link_to 'Back', idioms_path

app/views/idioms/index.html.haml
%h1 Listing idioms

%table
  %tr
    %th
    %th
    %th

  - @idioms.each do |idiom|
    %tr
      %td= idiom.title
      %td= idiom.description
      %td= link_to 'Show', idiom
      %td= link_to 'Edit', edit_idiom_path(idiom)
      %td= link_to 'Destroy', idiom, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Idiom', new_idiom_path

app/views/idioms/new.html.haml
%h1 New idiom

= render 'form'

= link_to 'Back', idioms_path

app/views/idioms/show.html.haml
%p#notice= notice
タイトル
= @idiom.title
意味
= @idiom.description

= link_to 'Edit', edit_idiom_path(@idiom)
\|
= link_to 'Back', idioms_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title IdiomPaper
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield